### ISSUE TITLE
项目重名会不会有点尴尬

### ISSUE THREAD

**Issue by c16ee5a6** [Chlience/V2RayC#1]
隔壁已经有一个mac的V2RayC项目了，万一这两个项目都火起来了，到时候会不会很尴尬？
https://github.com/gssdromen/V2RayC

另外60多M的安装包有点吓人，我知道这是Electron的锅，只是随便说说。

**Comment by Chlience** [comment]
emm的确是的说
关于项目重名问题什么的，一点都不尴尬嘛~
说不定最后我们还合并了呢

开个玩笑
而安装包大小问题确实需要解决，因为作者现在还在准备考试，准备在之后学习一下其他的方法构建应用，不一定会使用 Electron ，敬请期待吧
